### ISSUE TITLE
converting multiple files from directory

### ISSUE THREAD

**Issue by Krysasp** [tseemann/any2fasta#21]
Hi there. Is there command that converts files within single or different folders under one directory and output into separate folder?

**Comment by tseemann** [comment]
`any2fasta` works in a pipe so it can only do 1 file at a time.

You can use it with other tools like `for` loops in `bash` or GNU `parallel` to run it over a set of files if you need.

If you have a folder of GBK files for example:

`for F in *.gbk ; do any2fasta $F > $F.fasta ; done`

Or

`parallel 'any2fasta {} > {.}.fasta' ::: *.gbk`

**Comment by Krysasp** [comment]
ah, right. just realized GNU parallel. Thanks for helping !
