### ISSUE TITLE
Only converts first read of nanopore fastq.gz file

### ISSUE THREAD

**Issue by erinyoung** [tseemann/any2fasta#26]
I have some fastq.gz files from nanopore sequencing. They have a lot of reads.

```
$ wc -l nanopore_reads/*
  2337214 nanopore_reads/1326974.fastq.gz
   293071 nanopore_reads/3433012.fastq.gz
  2630285 total

```

But when I use any2fasta, I only get the first line:

```
$ any2fasta nanopore_reads/1326974.fastq.gz 
This is any2fasta 0.4.2
Opening 'nanopore_reads/1326974.fastq.gz'
Detected FASTQ format
Read 4 lines from 'nanopore_reads/1326974.fastq.gz'
>548c0b75-3444-4fb3-8a42-cedb213fe177 runid=fca3ca39efc128e221a14cb984aff5e59479f18e read=13 ch=131 start_time=2021-08-17T21:32:40Z flow_cell_id=FAN24319 protocol_group_id=UT-GXB02179-210817 sample_id=UT-GXB02179-210817 barcode=barcode06 barcode_alias=barcode06
TGTATCAAATAGCAAATCCATATGCAATTGGATTTCGAACTAATGTGTAATGCATACCAAATGGTGAGATAAGCCACAAAGGAACGTAGTTTGTATTTACCATTCAAACTCTAAATTACTTATTAAAACCTGAGAAGTGGGTTTCATTTATATAACTAAAGGCACTTTTCTAATTTAAGACCAGTCTTCCTCCAAATCTTCGATTACGAATAGTTAGTAATTTCTTCTTCATATTTTGATGTTGCCTCAGTTACTACAGCATTTCGACCACCTGTAACTCCATATCGGTCAAAGCCATTTTCAGCATCTCTAGAAGTTGTATTATTTCTGAAAGATAAACTTTTGCCTTACCATCTTTAATTAGACTAGCTTTGCCTCTTACATTTGGGCATTTCTTTTCTGGGATTTCAATGACGATTACATATGCTTGAGTTGCCATAATTTAATTACACCTTCTCAATTATGAAATCAGCCTTAGTTGTCATTCCACCACTAAAACTACTCTTGGGCAGTTAACTTAGCAGACTCTTCATCATCTATTTGACCGACTAAACTTTTTCAGGTGTATTTCTCGCAAAGAGCCAGAAAGTAGT
Wrote 1 sequences from FASTQ file.
Processed 1 files.
Done.
```

I was expecting each read to be exported to fasta format. Is there a flag somewhere that I'm missing?

**Comment by tseemann** [comment]
This is very weird.
I am unable to reproduce this error on our ONT files.
```
This is any2fasta 0.4.2
Opening 'ont.fastq.gz'
Detected FASTQ format
Read 16316 lines from 'ont.fastq.gz'
Wrote 4079 sequences from FASTQ file.
Processed 1 files.
Done.
```
I notice you run `wc -l` on .gz files - is that valid?

What does `seqkit stats` say for your files?

**Comment by tseemann** [comment]
@erinyoung thank you for sending your .fastq.gz file

I think I have figured out the problem
It seems to have been compressed with `bgzip` (block GZIP) and not regular `gzip`.
This is a special form of .gz for using with random access indices.

I am unable to make any2fasta work with bgzip as I am beholden to the Perl decompression interface.

I would not recommend any2fasta for FASTQ -> FASTA anyway.
Please use `seqkit fq2fa` instead.
It actually works with bgzip too.

**Comment by erinyoung** [comment]
Thank you for looking into this! These files were created via MinKnow, so I wasn't aware of how they were generated. I'll take a look at seqkit fq2fa

**Comment by tseemann** [comment]
@erinyoung i saw somewhere (forgot where) that in some pipleine on MinKnow they use either gzip or bgzip - it's a user setting somehwere. This could explain why my ONT data is fine but yours didn't work.
